version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres__container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./external/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5430:5432"
    restart: unless-stopped